#!/usr/bin/env python3
import json
import argparse

data_file = '/home/abner/.local/share/trfs/trfs.json'


def main():
    parser = argparse.ArgumentParser(
        prog = 'trfs',
        description='Gerenciador simples de dicio'
    )
    subparsers = parser.add_subparsers(dest='comando')
    subparsers.add_parser('criar').add_argument('texto')
    subparsers.add_parser('ls')
    subparsers.add_parser('rm').add_argument('texto')

    args = parser.parse_args()
    
    if args.comando == 'criar':
        with open(data_file, 'r', encoding='utf-8') as objeto_json:
            dici_py = json.load(objeto_json)
        novo_id = f'{int(str(list(dici_py.keys())[-1])[-1])+1:0>2}'
        dici_py[novo_id] = {args.texto: 'Elaborada'}
        with open(data_file, 'w', encoding='utf-8') as objeto_json:
            json.dump(dici_py, objeto_json)
        print(f'Tarefa "{args.texto}" criada')

    if args.comando == 'ls':
        with open(data_file, 'r', encoding='utf-8') as objeto_json:
            dicio = json.load(objeto_json)
        try:
            for ids in dicio.keys():
                chave = str(list(dicio[ids].keys())[0])
                print(f'{chave.title()}: {dicio[ids][chave]}')
        except Exception as e:
            print(f'{e} aaaa')
            print('Nenhuma tarefa adicionada')
    # if args.comando == 'rm':
    #     print(f'Removendo tarefa {args.texto}')
    #     try:
    #         dicio.pop(args.texto)
    #     except:
    #         print('Tarefa não encontrada')

if __name__ == '__main__':
    main()